[workspace]
members = [
  "ceno_emul",
  "ceno_host",
  "ceno_rt",
  "ceno_zkvm",
  "examples-builder",
  "examples",
  "mpcs",
  "multilinear_extensions",
  "sumcheck_macro",
  "poseidon",
  "sumcheck",
  "transcript",
]
resolver = "2"

[workspace.package]
categories = ["cryptography", "zk", "blockchain", "ceno"]
edition = "2021"
keywords = ["cryptography", "zk", "blockchain", "ceno"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scroll-tech/ceno"
version = "0.1.0"

[workspace.dependencies]
anyhow = { version = "1.0", default-features = false }
cfg-if = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }
crossbeam-channel = "0.5"
itertools = "0.13"
num-derive = "0.4"
num-traits = "0.2"
num-bigint = { version = "0.4", default-features = false }
p3-challenger = { git = "https://github.com/plonky3/plonky3", rev = "973088b" }
p3-field = { git = "https://github.com/plonky3/plonky3", rev = "973088b" }
p3-goldilocks = { git = "https://github.com/plonky3/plonky3", rev = "973088b" }
p3-mds = { git = "https://github.com/Plonky3/Plonky3.git", rev = "973088b" }
p3-poseidon = { git = "https://github.com/plonky3/plonky3", rev = "973088b" }
p3-poseidon2 = { git = "https://github.com/plonky3/plonky3", rev = "973088b" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "973088b" }
paste = "1"
poseidon = { path = "./poseidon" }
pprof2 = { version = "0.13", features = ["flamegraph"] }
prettytable-rs = "^0.10"
proptest = "1"
rand_xorshift = "0.3"
rand = "0.9"
rand_chacha = "0.9"
rayon = "1.10"
secp = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tracing = { version = "0.1", features = [
  "attributes",
] }
tracing-forest = { version = "0.1.6" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
lto = "thin"
# We are running our tests with optimizations turned on to make them faster.
# Please turn optimizations off, when you want accurate stack traces for debugging.
opt-level = 2

[profile.dev.package."*"]
# Set the default for dependencies in Development mode.
opt-level = 3

[profile.release]
lto = "thin"
