[package]
categories.workspace = true
description = "Transcript generation for Ceno"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "transcript"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
crossbeam-channel.workspace = true
ff.workspace = true
ff_ext = { path = "../ff_ext" }
goldilocks.workspace = true
serde.workspace = true
p3-field.workspace = true
p3-goldilocks.workspace = true
p3-poseidon.workspace = true
p3-poseidon2.workspace = true
p3-challenger.workspace = true
p3-mds.workspace = true
p3-symmetric.workspace = true

