[package]
categories.workspace = true
description = "Poseidon hash function"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "poseidon"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
criterion.workspace = true
ff.workspace = true
goldilocks.workspace = true
serde.workspace = true
ff_ext = { path = "../ff_ext" }
unroll = "0.1"
p3-field.workspace = true
p3-goldilocks.workspace = true
p3-poseidon.workspace = true
p3-mds.workspace = true
p3-symmetric.workspace = true

[dev-dependencies]
ark-std.workspace = true
plonky2.workspace = true
rand.workspace = true

[[bench]]
harness = false
name = "hashing"
